-- CREATOR · valores iniciales. Todo es editable desde /admin.

insert into ajustes (id, marca, precios, ia, crm) values (
  1,
  '{
    "nombre": "AiUDA",
    "eslogan_es": "Sistemas de inteligencia artificial a la medida de tu negocio",
    "eslogan_en": "AI systems tailored to your business",
    "logo_url": "/brand/logo.png",
    "color_primario": "#4B2BD6",
    "color_acento": "#12B886",
    "email": "",
    "telefono": "",
    "sitio_web": "",
    "direccion": "Ecuador",
    "validez_dias": 15
  }',
  '{
    "moneda": "USD",
    "iva_pct": 15,
    "margen_minimo_mensual": 150,
    "precio_usuario_extra": 15,
    "costo_infra_base": 45,
    "anticipo_pct": 50,
    "modelo_por_usuario": 45,
    "modelo_volumen_base": 120
  }',
  '{
    "proveedor": "anthropic",
    "modelo_anthropic": "claude-opus-5",
    "modelo_openai": "gpt-4.1",
    "modelo_transcripcion": "gpt-4o-transcribe",
    "esfuerzo": "high"
  }',
  '{
    "activo": true,
    "enviar_al_crear_propuesta": false,
    "service_type": "consultoria",
    "source": "otro"
  }'
);

insert into catalogo
  (codigo, tipo, categoria, nombre_es, nombre_en, descripcion_es, descripcion_en,
   caracteristicas_es, caracteristicas_en, resuelve, incluye,
   precio_setup, precio_mensual, costo_setup, costo_mensual, usuarios_incluidos, volumen, semanas, estado, orden)
values
-- ============================== PAQUETES ==============================
('IAGENTE_WA', 'paquete', 'atencion',
 'iAgente WhatsApp + Chatwoot', 'WhatsApp AI Agent + Chatwoot',
 'Agente de IA que atiende WhatsApp 24/7: responde, califica, transcribe audios, lee imágenes, agenda y escala a un humano. Bandeja compartida en Chatwoot para el equipo.',
 'AI agent that handles WhatsApp 24/7: answers, qualifies, transcribes voice notes, reads images, books appointments and escalates to a human. Shared Chatwoot inbox for the team.',
 array['Respuesta inmediata 24/7','Transcripción de audios y lectura de imágenes','Calificación del prospecto','Agenda de citas','Escalamiento a humano','Bandeja compartida Chatwoot'],
 array['Instant 24/7 replies','Voice note transcription and image reading','Lead qualification','Appointment booking','Human handoff','Shared Chatwoot inbox'],
 array['respuesta lenta','whatsapp saturado','fuera de horario','leads perdidos','atencion al cliente','preguntas repetitivas'],
 '{}', 2500, 190, 600, 40, 3,
 '{"unidad_es":"conversaciones","unidad_en":"conversations","incluido":1000,"precio_excedente":0.15,"costo_unitario":0.04}',
 3, 'listo', 10),

('CRM_BASICO', 'paquete', 'crm',
 'CRM IA · Básico', 'AI CRM · Basic',
 'CRM con inteligencia artificial para ordenar ventas: leads, pipeline visual, calificación automática con IA, tablero de ventas y agenda conectada a Google Calendar.',
 'AI-powered CRM to organize sales: leads, visual pipeline, automatic AI lead scoring, sales dashboard and scheduling synced with Google Calendar.',
 array['Leads y ficha 360° del cliente','Pipeline Kanban','Calificación de leads con IA','Tablero de ventas','Citas + Google Calendar','Automatizaciones n8n base'],
 array['Leads and 360° customer record','Kanban pipeline','AI lead scoring','Sales dashboard','Appointments + Google Calendar','Base n8n automations'],
 array['desorden comercial','excel','no se sabe en que etapa','seguimiento manual','perdida de clientes','sin datos de ventas'],
 array['CITAS'], 3500, 250, 900, 80, 5, null, 4, 'listo', 20),

('CRM_OPERATIVO', 'paquete', 'crm',
 'CRM IA · Operativo', 'AI CRM · Operations',
 'Todo el Básico más la operación automatizada: seguimientos por WhatsApp con supervisor IA, cotizador, documentos con IA, reportes y vigía diario que alerta lo urgente.',
 'Everything in Basic plus automated operations: WhatsApp follow-ups with an AI supervisor, quoting, AI documents, reports and a daily watchdog that flags what is urgent.',
 array['Todo lo del Básico','Seguimientos automáticos WhatsApp + supervisor IA','Cotizador con PDF','Documentos con IA','Reportes y exportación','Vigía diario con alertas'],
 array['Everything in Basic','Automated WhatsApp follow-ups + AI supervisor','Quoting tool with PDF','AI documents','Reports and exports','Daily watchdog alerts'],
 array['seguimientos olvidados','cotizaciones lentas','documentos manuales','no hay reportes','procesos repetitivos'],
 array['CITAS','SEGUIMIENTOS','COTIZADOR','DOCUMENTOS','VIGIA','PANEL'], 6500, 390, 1600, 140, 10, null, 6, 'listo', 30),

('CRM_GERENCIAL', 'paquete', 'crm',
 'CRM IA · Gerencial', 'AI CRM · Executive',
 'Todo el Operativo más la capa de dirección: Super Agente que conoce todo el CRM y gerencia, gerentes IA por área, llamadas con IA, prospección automática y panel de dirección.',
 'Everything in Operations plus the management layer: a Super Agent that knows the whole CRM and manages, AI managers per department, AI voice calls, automated prospecting and an executive panel.',
 array['Todo lo del Operativo','Super Agente + gerentes IA por área','Llamadas IA entrantes y salientes (200 min)','Prospección IA','Panel de dirección y control de gasto IA','Escalamiento por llamada al gerente'],
 array['Everything in Operations','Super Agent + AI department managers','Inbound and outbound AI calls (200 min)','AI prospecting','Executive panel and AI spend control','Escalation calls to the manager'],
 array['el dueno no tiene visibilidad','depende de personas','no llaman a los leads','falta prospeccion','decisiones sin datos'],
 array['CITAS','SEGUIMIENTOS','COTIZADOR','DOCUMENTOS','VIGIA','PANEL','SUPERAGENTE','LLAMADAS','PROSPECCION'], 12000, 650, 3000, 250, 20,
 '{"unidad_es":"minutos de llamada","unidad_en":"call minutes","incluido":200,"precio_excedente":0.35,"costo_unitario":0.18}',
 10, 'listo', 40),

('CRM_SERVICIOS', 'paquete', 'vertical',
 'CRM + Agente para negocios de servicios', 'CRM + Agent for service businesses',
 'Producto vertical probado en producción: CRM de pedidos, cola de trabajo, catálogo de precios y agente de WhatsApp que cotiza con precios reales y agenda recogidas/entregas.',
 'Production-proven vertical product: order CRM, work queue, price catalog and a WhatsApp agent that quotes with real prices and schedules pickups/deliveries.',
 array['Clientes, pedidos y cola de trabajo','Catálogo de servicios y precios','Agente WhatsApp que cotiza','Agenda de recogidas y entregas','Reportes'],
 array['Customers, orders and work queue','Service and price catalog','WhatsApp agent that quotes','Pickup and delivery scheduling','Reports'],
 array['pedidos desordenados','cotizar a mano','logistica','lavanderia','limpieza','servicios recurrentes'],
 '{}', 5500, 290, 1300, 90, 5,
 '{"unidad_es":"conversaciones","unidad_en":"conversations","incluido":1000,"precio_excedente":0.15,"costo_unitario":0.04}',
 5, 'listo', 50),

-- ============================== MÓDULOS ==============================
('LLAMADAS', 'modulo', 'voz',
 'Llamadas con IA', 'AI Voice Calls',
 'Agente de voz que llama y recibe llamadas: califica, agenda, deja la transcripción y el resumen en la ficha del cliente y avanza la etapa.',
 'Voice agent that makes and takes calls: qualifies, books, stores the transcript and summary on the customer record and advances the stage.',
 array['Llamadas salientes y entrantes','Transcripción y resumen automático','Agenda en Calendar','Número local'],
 array['Outbound and inbound calls','Automatic transcript and summary','Calendar booking','Local number'],
 array['no se llama a los leads','llamadas perdidas','recepcion','confirmar citas','cobranza'],
 '{}', 2000, 150, 500, 45, 0,
 '{"unidad_es":"minutos de llamada","unidad_en":"call minutes","incluido":200,"precio_excedente":0.35,"costo_unitario":0.18}',
 3, 'listo', 110),

('SUPERAGENTE', 'modulo', 'direccion',
 'Super Agente + gerentes IA', 'Super Agent + AI managers',
 'Un agente que sabe todo lo del CRM: responde preguntas del negocio, mueve etapas, agenda mensajes y gerencia. Incluye gerentes IA por departamento y acceso por WhatsApp para el dueño.',
 'An agent that knows everything in the CRM: answers business questions, moves stages, schedules messages and manages. Includes AI managers per department and WhatsApp access for the owner.',
 array['Chat con acceso a todos los datos','Acciones reales en el CRM','Gerentes IA por área','Consulta por WhatsApp'],
 array['Chat with access to all data','Real actions in the CRM','AI managers per area','WhatsApp access'],
 array['el dueno no tiene visibilidad','reportes manuales','decisiones lentas','gerencia'],
 '{}', 3000, 120, 700, 35, 0, null, 3, 'listo', 120),

('SEGUIMIENTOS', 'modulo', 'ventas',
 'Seguimientos automáticos + supervisor IA', 'Automated follow-ups + AI supervisor',
 'Secuencias de WhatsApp por etapa del cliente, con un supervisor IA que revisa cada mensaje antes de enviarlo.',
 'WhatsApp sequences by customer stage, with an AI supervisor that reviews every message before it is sent.',
 array['Secuencias por etapa','Mensajes manuales programados','Supervisor IA de calidad','Plantillas de Meta'],
 array['Stage-based sequences','Scheduled manual messages','AI quality supervisor','Meta templates'],
 array['seguimientos olvidados','leads se enfrian','no hay recontacto'],
 '{}', 1800, 90, 450, 25, 0, null, 2, 'listo', 130),

('PROSPECCION', 'modulo', 'ventas',
 'Prospección con IA', 'AI Prospecting',
 'Busca empresas y personas que encajan con el cliente ideal, las puntúa, evita duplicados y las convierte en leads cumpliendo la LOPDP.',
 'Finds companies and people matching the ideal customer, scores them, avoids duplicates and converts them into leads in line with data-protection law.',
 array['Búsqueda web con IA','Puntuación de encaje','Deduplicación','Base legal LOPDP'],
 array['AI web search','Fit scoring','Deduplication','Data-protection legal basis'],
 array['falta de clientes nuevos','dependencia de referidos','prospeccion manual'],
 '{}', 1500, 90, 400, 30, 0, null, 2, 'listo', 140),

('COTIZADOR', 'modulo', 'ventas',
 'Cotizador web con PDF', 'Web quoting tool with PDF',
 'Cotizador en línea con las tablas de precio del negocio: el cliente cotiza solo, descarga un PDF con marca y queda registrado como lead.',
 'Online quoting tool with the business price tables: customers quote themselves, download a branded PDF and are captured as leads.',
 array['Cotización paso a paso','PDF con marca e IVA','Captura de lead','Precios editables'],
 array['Step-by-step quote','Branded PDF with tax','Lead capture','Editable prices'],
 array['cotizaciones lentas','cotizar a mano','errores de precio'],
 '{}', 1800, 60, 450, 10, 0, null, 2, 'listo', 150),

('MARKETING', 'modulo', 'marketing',
 'Marketing con IA', 'AI Marketing',
 'Estrategia mensual, calendario de contenido, creación de piezas y publicación automática en Instagram y Facebook.',
 'Monthly strategy, content calendar, asset creation and automatic publishing to Instagram and Facebook.',
 array['Plan de contenidos mensual','Imágenes y video con IA','Publicación automática','Métricas'],
 array['Monthly content plan','AI images and video','Automatic publishing','Metrics'],
 array['redes abandonadas','no hay contenido','marketing caro','poca visibilidad'],
 '{}', 2500, 180, 600, 70, 0, null, 3, 'listo', 160),

('ADSBOOM', 'modulo', 'marketing',
 'AdsBoom · Meta Ads con IA', 'AdsBoom · AI Meta Ads',
 'Plan de campañas con IA, creativos (imagen, carrusel, reel), publicación en Meta y sincronización de métricas. La pauta la paga el cliente.',
 'AI campaign plan, creatives (image, carousel, reel), Meta publishing and metrics sync. Ad spend is paid by the client.',
 array['Plan de campaña con aprobación','Creativos con IA','Publicación en Meta','Métricas sincronizadas'],
 array['Campaign plan with approval','AI creatives','Meta publishing','Synced metrics'],
 array['anuncios sin resultado','agencia cara','no se mide la pauta'],
 '{}', 3000, 200, 700, 60, 0, null, 3, 'listo', 170),

('DOCUMENTOS', 'modulo', 'operacion',
 'Documentos con IA', 'AI Documents',
 'Plantillas del negocio (contratos, propuestas, actas) redactadas con IA y exportadas a Word o PDF.',
 'Business templates (contracts, proposals, minutes) drafted with AI and exported to Word or PDF.',
 array['Plantillas propias','Redacción con IA','Word y PDF'],
 array['Custom templates','AI drafting','Word and PDF'],
 array['documentos manuales','contratos lentos','errores en documentos'],
 '{}', 1200, 50, 300, 12, 0, null, 2, 'listo', 180),

('VIGIA', 'modulo', 'direccion',
 'Vigía diario + escalamiento', 'Daily watchdog + escalation',
 'Revisa el negocio cada día y avisa lo urgente: campana en el sistema, WhatsApp y, si es crítico, llamada del gerente IA.',
 'Checks the business every day and flags what is urgent: in-app bell, WhatsApp and, when critical, a call from the AI manager.',
 array['Revisión diaria automática','Alertas por WhatsApp','Llamada en casos críticos','Bitácora de reuniones'],
 array['Automatic daily review','WhatsApp alerts','Call on critical issues','Meeting log'],
 array['problemas se detectan tarde','el dueno se entera tarde'],
 '{}', 900, 50, 250, 12, 0, null, 1, 'listo', 190),

('PANEL', 'modulo', 'direccion',
 'Panel de dirección + reportes', 'Executive panel + reports',
 'Ventas, operación, gasto de IA, salud del sistema y auditoría en un solo lugar, con reportes exportables.',
 'Sales, operations, AI spend, system health and audit in one place, with exportable reports.',
 array['Indicadores clave','Gasto de IA','Auditoría','Exportar a PDF/Excel'],
 array['Key metrics','AI spend','Audit log','Export to PDF/Excel'],
 array['sin datos','reportes manuales','sin control'],
 '{}', 1000, 40, 250, 5, 0, null, 1, 'listo', 200),

('CITAS', 'modulo', 'atencion',
 'Citas + Calendar + recordatorios', 'Appointments + Calendar + reminders',
 'Agenda conectada a Google Calendar con recordatorio automático por WhatsApp 24 horas antes.',
 'Scheduling connected to Google Calendar with an automatic WhatsApp reminder 24 hours before.',
 array['Google Calendar','Recordatorio 24 h por WhatsApp','Historial de citas'],
 array['Google Calendar','24h WhatsApp reminder','Appointment history'],
 array['citas olvidadas','ausentismo','agenda en papel'],
 '{}', 800, 40, 200, 5, 0, null, 1, 'listo', 210),

('INMO_MERCADO', 'modulo', 'inmobiliario',
 'Estudio de mercado + Index (inmobiliario)', 'Market study + Index (real estate)',
 'Análisis comparativo de mercado con investigación web citada, termómetro de precios por zona y noticias del sector.',
 'Comparative market analysis with cited web research, price thermometer by area and sector news.',
 array['Estudio ACM con fuentes','Precio por m² por zona','Noticias diarias','Exportar a PDF/Word'],
 array['Cited market study','Price per m² by area','Daily news','Export to PDF/Word'],
 array['inmobiliaria','precios de mercado','captacion de propiedades'],
 '{}', 2500, 120, 600, 40, 0, null, 3, 'listo', 300),

('INMO_AVALUOS', 'modulo', 'inmobiliario',
 'Avalúos con IA (inmobiliario)', 'AI Appraisals (real estate)',
 'Avalúos por método comparativo, de costo, de renta y residual; normativa municipal, comparables automáticos y análisis de fotos.',
 'Appraisals by comparable, cost, income and residual methods; zoning rules, automatic comparables and photo analysis.',
 array['4 métodos de valoración','Comparables automáticos','Análisis de fotos','Exportar con firma'],
 array['4 valuation methods','Automatic comparables','Photo analysis','Signed export'],
 array['avaluos lentos','inmobiliaria','valoracion'],
 '{}', 3500, 150, 900, 45, 0, null, 4, 'listo', 310),

-- ============================== SERVICIOS ==============================
('LEVANTAMIENTO', 'servicio', 'consultoria',
 'Levantamiento documental de procesos', 'Process documentation survey',
 'Mapeo y documentación de los procesos del negocio: entrevistas, flujos, responsables e indicadores. Base para automatizar sin romper la operación.',
 'Mapping and documentation of business processes: interviews, flows, owners and KPIs. The foundation to automate without breaking operations.',
 array['Entrevistas por área','Flujos de proceso','Matriz de responsables','Indicadores y recomendaciones'],
 array['Interviews per area','Process flows','Responsibility matrix','KPIs and recommendations'],
 array['procesos no documentados','depende de personas','caos operativo','crecimiento desordenado'],
 '{}', 2800, 0, 900, 0, 0, null, 3, 'listo', 400),

('PITCH_SITE', 'servicio', 'marketing',
 'Sitio de presentación para inversionistas', 'Investor pitch website',
 'Sitio interactivo y animado para presentar un proyecto a inversionistas o compradores: mapa, galería, calculadora de inversión.',
 'Interactive animated website to pitch a project to investors or buyers: map, gallery, investment calculator.',
 array['Diseño animado','Calculadora de inversión','Mapa y galería'],
 array['Animated design','Investment calculator','Map and gallery'],
 array['levantar capital','presentar proyecto','inversionistas'],
 '{}', 2200, 0, 700, 0, 0, null, 2, 'listo', 410),

('CAPACITACION', 'servicio', 'consultoria',
 'Capacitación del equipo', 'Team training',
 'Talleres prácticos para que el equipo adopte el sistema desde el primer día.',
 'Hands-on workshops so the team adopts the system from day one.',
 array['2 talleres de 3 horas','Manual de usuario','Grabaciones'],
 array['2 workshops of 3 hours','User manual','Recordings'],
 array['el equipo no usa el sistema','resistencia al cambio'],
 '{}', 400, 0, 100, 0, 0, null, 1, 'listo', 420);
